// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanctionSearchAPI.Data;

namespace SanctionSearchAPI.Migrations
{
    [DbContext(typeof(WSDataContextBroker))]
    partial class WSDataContextBrokerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SanctionSearchAPI.Models.LocalWatchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("_afm_")
                        .HasMaxLength(100);

                    b.Property<string>("_arithmos_diavatiriou_")
                        .HasMaxLength(100);

                    b.Property<string>("_arithmos_dieuthinsis_")
                        .HasMaxLength(100);

                    b.Property<string>("_arithmos_nhologiou_")
                        .HasMaxLength(100);

                    b.Property<string>("_eidos_enimerwsis_")
                        .HasMaxLength(100);

                    b.Property<string>("_epaggelma_titlos_")
                        .HasMaxLength(100);

                    b.Property<string>("_eponumo_eponumia_")
                        .HasMaxLength(100);

                    b.Property<string>("_ethnikothta_")
                        .HasMaxLength(100);

                    b.Property<string>("_fylo_")
                        .HasMaxLength(100);

                    b.Property<string>("_glwssa_")
                        .HasMaxLength(100);

                    b.Property<string>("_hmerominia_prosthikis_tropopoiis_")
                        .HasMaxLength(100);

                    b.Property<string>("_kataxorhmenh_xorhtikothta_")
                        .HasMaxLength(100);

                    b.Property<string>("_kodikos1_")
                        .HasMaxLength(100);

                    b.Property<string>("_kodikos2_")
                        .HasMaxLength(100);

                    b.Property<string>("_kodikos3_")
                        .HasMaxLength(100);

                    b.Property<string>("_kodikos4_")
                        .HasMaxLength(100);

                    b.Property<int?>("_kodikos_monados_");

                    b.Property<string>("_length_")
                        .HasMaxLength(100);

                    b.Property<string>("_mesaio_onoma_")
                        .HasMaxLength(100);

                    b.Property<string>("_mikro_onoma_")
                        .HasMaxLength(100);

                    b.Property<int?>("_morfi_");

                    b.Property<int?>("_o__aykson_arithmos_eggrafis_");

                    b.Property<string>("_odos_")
                        .HasMaxLength(100);

                    b.Property<string>("_oloklhro_onoma_")
                        .HasMaxLength(100);

                    b.Property<string>("_parapompi_")
                        .HasMaxLength(50);

                    b.Property<string>("_ploiokthths_")
                        .HasMaxLength(100);

                    b.Property<string>("_position_")
                        .HasMaxLength(100);

                    b.Property<int?>("_proeleysi_");

                    b.Property<string>("_shmaia_")
                        .HasMaxLength(100);

                    b.Property<string>("_sxolia1_")
                        .HasMaxLength(100);

                    b.Property<string>("_sxolia2_")
                        .HasMaxLength(100);

                    b.Property<string>("_sxolia3_")
                        .HasMaxLength(100);

                    b.Property<string>("_syndesmos_sto_antistoixo_nomiko__")
                        .HasMaxLength(100);

                    b.Property<string>("_topothesia_gennhshs_")
                        .HasMaxLength(100);

                    b.Property<string>("_typos_ploiou_")
                        .HasMaxLength(100);

                    b.Property<string>("_xora_ekdosis_diavatiriou_")
                        .HasMaxLength(100);

                    b.Property<string>("_xora_gennhshs_")
                        .HasMaxLength(50);

                    b.Property<string>("_xorhtikothta_")
                        .HasMaxLength(100);

                    b.Property<string>("_yphkoothta_")
                        .HasMaxLength(100);

                    b.Property<string>("birth_country")
                        .HasMaxLength(100);

                    b.Property<string>("city")
                        .HasMaxLength(100);

                    b.Property<string>("country")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("date_birth")
                        .HasColumnType("datetime");

                    b.Property<string>("details")
                        .HasMaxLength(100);

                    b.Property<string>("dieuthinsi1")
                        .HasMaxLength(100);

                    b.Property<string>("dieuthinsi2")
                        .HasMaxLength(100);

                    b.Property<string>("dieuthinsi3")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("discovery_date")
                        .HasColumnType("datetime");

                    b.Property<string>("first_name")
                        .HasMaxLength(100);

                    b.Property<string>("full_name")
                        .HasMaxLength(100);

                    b.Property<string>("identity_country_1")
                        .HasMaxLength(100);

                    b.Property<string>("identity_country_2")
                        .HasMaxLength(100);

                    b.Property<string>("identity_type_1")
                        .HasMaxLength(100);

                    b.Property<string>("identity_type_2")
                        .HasMaxLength(100);

                    b.Property<string>("last_name")
                        .HasMaxLength(100);

                    b.Property<string>("middle_name")
                        .HasMaxLength(100);

                    b.Property<string>("other_names")
                        .HasMaxLength(100);

                    b.Property<string>("place_of_birth")
                        .HasMaxLength(100);

                    b.Property<string>("sanctions_program")
                        .HasMaxLength(100);

                    b.Property<string>("tax_id")
                        .HasMaxLength(100);

                    b.Property<string>("watchlist_org")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("LocalWatchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
